name: PR checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-checks-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  build-images:
    uses: ./.github/workflows/build_images.yml
